function rawString=reportString(fid,id,myString)
% function rawString=reportString(fid,id,myString)
%
% Cunning recursive function used to build an HTML file for displaying the
% imaging results. File is generated by generateRecordingReport.m
%
% Rob Campbell - October 2009
%  
%----------------------------------------------------------------------
%
%<<header>>
%<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
%"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
%<!--- MATLAB GENERATED DATA ANALYSIS REPORT WITH SVG FIGURES --->
%<!--- Rob Campbell, SVG figures by Juerg Schwizer (plot2svg) --->
%
%<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
%
%<head> 
%<title>Report of DELTA1</title>
%<script type="text/javascript">
%  function swapImage(){
%  var dropd = document.getElementById("kcSwapper");
%  document.getElementById("kcdff").data = dropd.value;
%   };
%</script>
%<</header>>
%<<footer>>
%</body>
%</html>
%<</footer>>
%<<svg>>
%<object type="image/svg+xml" data="./DELTA1" width="DELTA2" height="DELTA3"></object>
%<</svg>>
%<<jpg>>
%<img id="DELTA4" src="./DELTA1" width="DELTA2" height="DELTA3" />
%<</jpg>>
%<<jpgdiv>>
%<div id=DELTA5 style="border:1px black solid; 
%            background:url(./DELTA1) no-repeat top left;
%            width:DELTA2px;height:DELTA3px;float:left;">
% <p style="padding-left:5px;">
%  <span style="color:red;font-size:0.75em">DELTA4</span>
% </p>
%</div>
%<</jpgdiv>>
%<<box1start>>
%<div class="box1" style="border:1px black dashed;
%                  width:DELTA1px;background-color:#9999ff;">
%<</box1start>>
%<<boxend>>
%</div>
%  
%<</boxend>>
%----------------------------------------------------------------------

  
  

if nargin<3, myString={}; end  
if ~iscell(myString); myString={myString};end
id=lower(id);

%Happy way of generating the raw string
rawString=regexp(help('reportString.m'),...
                 sprintf('<<%s>>(.*)<</%s>>',id,id),...
                 'tokens');

if isempty(rawString)
  error('id class not found')
else
  rawString=rawString{1}{1};
end

%Customize and print the string 
if ~isempty(myString)
  for i=1:length(myString)
    rawString=regexprep(rawString,['DELTA',num2str(i)],myString{i});
  end  
end


fprintf(fid,rawString);
