function data=importFluoView(fname,index,bitDepth)
% Import a tiff generated by FluoView
%
% function data=importFluoView(fname,index,bitDepth)
%
% Purpose
% FluoView saves each trial as a separate multi-image tiff. This
% file imports one of these tiffs, saving it as a .mat file for
% using with subsequent functions. It also creates a data structure
% which can be turned into a twoPhoton object.
%
% Inputs
% * fname - a string indicating which file to load. 
% * index - the index in the structure into which this data will be
%   stored. index is optional and ==1 by default.
% * bitDepth - The digitisation resolution of the image in
% bits. Optional. 
%
% NOTE: This function is not quite finised but it should get you
% started. You might need to modify it to extract more meta-data.
%
% Rob Campbell 


if nargin<2
    index=1; 
end

if nargin<3
    % Yuk! Bitdepth is hard coded. It would be best if you can
    % extract the bitdepth from the tiff or another source. 
    bitDepth=10; %best guess for the bit depth
end



[imageStack,imageInfo]=load3Dtiff(fname);


imageStack=imageStack/2^bitDepth; %to normalise image 

%now we pull out all the useful meta-data from imageInfo
id=imageInfo(1).ImageDescription;


%e.g. SecondsPerScanLine=0.002116
tmp=regexp(id,'SecondsPerScanLine=(\d+\.\d+)','tokens');
tmp=str2double(tmp{1}{1});
data.info.SecondsPerScanLine=tmp;

%e.g. DelayToFirstImagePixelInSecs=0.009176
tmp=regexp(id,'DelayToFirstImagePixelInSecs=(\d+\.\d+)','tokens');
tmp=str2double(tmp{1}{1});
data.info.DelayToFirstImagePixelInSecs=tmp;

%tmp=imageInfo(1).Height;
%data.info.LineNumber=tmp;

% Calculate the frame rate
% I am unsure why 0.1 is being added here:
%And before we figure out if there is/how to ripe out the "resting time"
%information, we would adding up it manually as value of 0.1s of which we
%generally got.

tmp=size(imageStack,1)*data.info.SecondsPerScanLine+...
    data.info.DelayToFirstImagePixelInSecs+0.1;
data.info.framePeriod=tmp;


data.relativeFrameTimes=zeros(1,size(imageStack,3)); %fill with nothing

%These are necessary for later functions to work
data.info.rawDataDir=pwd;
data.info.stimIndex=index;

 
%Save the imported imageStack as a .mat file in the data directory
data.info.rawDataFile=sprintf('rawData%d',index);
eval([data.info.rawDataFile,'=imageStack;']) 
fileStr=[data.info.rawDataDir,'/',data.info.rawDataFile];
save(fileStr,data.info.rawDataFile)
