%% importFluoView
% Import a tiff generated by FluoView
%
% |function data=importFluoView(fname,index,bitDepth)|
%
%% Purpose
% FluoView saves each trial as a separate multi-image tiff. This
% file imports one of these tiffs, saving it as a .mat file for
% using with subsequent functions. It also creates a data structure
% which can be turned into a twoPhoton object.
%
%% Inputs
% * |fname| - a string indicating which file to load. 
% * |index| - the index in the structure into which this data will be
% stored. index is optional and ==1 by default.
% * |bitDepth| - The digitisation resolution of the image in
% bits. Optional. 
%
%% Note
% This function is not quite finised but it should get you
% started. You might need to modify it to extract more meta-data.
