function PUBLISH_ALL

textprogressbar('Publishing Files: ');




importing={'addDatData.m',...
           'addStimParams.m',...
           'importFluoView.m',...
           'importFluoViewBatch.m',...
           'importPVtree.m',...
           'importScanImage.m',...
           'importSItree.m',...
           'prairieXML_2_Matlab.m',...
           'readPRM.m',...
           'readPVdat.m',...
           'generateDFFobject',...
           'twoPImportBatch.m'};

preprocess={'filterImageStack.m',...
            'doPhotoBleachCorrection',...
            'showPhotoBleachFit.m'};

motionCorrect={'alignStack.m',...
               'alignRepeats.m',...
               'apply_ffttrans.m',...
               'apply_demon.m',...
               'apply_elastix.m',...
               'apply_gkerr.m',...
               'apply_symmetric',...
               'regParams.m',...
               'visualiseDrift.m',...
               'visualiseDriftMovie.m'};

ROI={
    'selectROIs.m',...
    'addROIstats.m',...
    'ROI_add.m',...
    'ROI_autodetectFancy',...
    'ROI_batch.m',...
    'plotROIstats.m',...
    'whichROIsAreSignificant.m',...
    'nNeurons2p.m'};

popPlots={'odour3Dplot.m',...
          'odourDendrogram.m',...
          'overlayDFFandBaseline.m',...
          'overlayDFFs.m'};

display={          
    'playMovie.m',...
    'responseTimeCourse.m',...
    'roiTimeCourse.m',...
    'responseMagByPresentation.m',...
    'responseTimeCourseByOdour.m',...
    'colorDepth.m',...
    'colorResponse.m',...
    'imageStackCorr.m',...
    'cleanMeanDFF.m',...
    'showSelectedKCs.m'};

utils={'imagingAnalysis_load3Dtiff.m',...
       'imagingAnalysis_mat2im.m',...
       'imagingAnalysis_meanFromTif.m',...
       'getOdourNames.m',...
       'data2libsvm.m',...
       'Kalman_Stack_Filter.m',...
       'patch2blender.m',...
       'responsePeriodFrames.m',...
       'imagingAnalysis_save3Dtiff.m',...
       'imagingAnalysis_tiffFrames.m',...
       'updateDataDir.m',...
       'zExplorer.m'};

functionsByCat={'imagingAnalysis_functions_by_cat.m',...
    motionCorrect{:}};
    


intros={...
    'AnalysisSteps.m',...
    'imagingAnalysis_features.m',...
    'imagingAnalysis_product_page.m',...
    'imagingAnalysis_system_requirements.m',...'
    'imagingAnalysis_getting_started.m',...
    'imagingAnalysis_release_notes.m',...
    'imagingAnalysis_user_guide.m'};
    
tutes={...
'imagingAnalysis_importing.m',...
'imagingAnalysis_preprocess.m',...
 'imagingAnalysis_display.m'};
%'imagingAnalysis_neurons.m',...
%    'imagingAnalysis_display.m'};
 
examples={...    
    'imagingAnalysis_examples.m',...
    'tiffs.m',...
    'simpleROI.m',...
      };


files=[...
    functionsByCat,...
    intros,...
    examples];
    
files=[{'imagingAnalysis_getting_started.m','selectROIs.m','addROIstats.m','imagingAnalysis_neurons.m'}];

options.outputDir='../';
cwd=pwd;
for ii=1:length(files)
    %textprogressbar(round((ii/length(files)*100)));
    fprintf('%s\n',files{ii})
    publish(files{ii},options);
    cd(cwd)
end

textprogressbar(' done!')
